%%
%% This is file `ydoc.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% ydoc.dtx  (with options: `class')
%% 
%% Copyright (c) 2010 by Martin Scharrer <martin@scharrer-online.de>
%% WWW: http://latex.scharrer-online.de/
%%
%% This work may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License, either version 1.3
%% of this license or (at your option) any later version.
%% The latest version of this license is in
%%   http://www.latex-project.org/lppl.txt
%% and version 1.3 or later is part of all distributions of LaTeX
%% version 2005/12/01 or later.
%%
%% This work has the LPPL maintenance status `maintained'.
%%
%% The Current Maintainer of this work is Martin Scharrer.
%%
%% This work consists of the files ydoc.dtx and ydoc.ins
%% and the derived file ydoc.cls, ydoc.sty, ydoc-code.sty,
%% ydoc-expl.sty and ydoc-desc.sty.
%%
\RequirePackage{svn-prov}[2010/04/03]
\ProvidesClassSVN
    {$Id: ydoc.dtx 1847 2010-04-10 10:57:11Z martin $}
    [v0.1alpha]
   [ydoc class: document LaTeX class and packages]
\LoadClassWithOptions{article}
%%\RequirePackage{doc}
\RequirePackage{ydoc}
\endinput
%%
%% End of file `ydoc.cls'.
